# This workflow will publish a package to npm when changes are pushed to the main branch

name: Ritmin Cli

on:
  push:
    branches:
      - main

jobs:
  publish-yarn:
    runs-on: windows-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true  
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://registry.npmjs.org/
      - run: yarn install
      
      # Add these steps to configure Git
      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - run: yarn version --patch # Increase the version number by a patch increment
      - run: yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
